- name: Configure Proxy
  hosts: all
  become: true
  tasks:
    - name: Create proxy.conf file
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/proxy.conf
        mode: 0664
        content: |
          Acquire::http::Proxy "http://192.168.123.249:8080/";
          Acquire::https::Proxy "http://192.168.123.249:8080/"
      notify: Reload Bashrc

    - name: Update ~/.bashrc file
      ansible.builtin.lineinfile:
        dest: ~/.bashrc
        line: |
          export HTTP_PROXY="http://192.168.123.249:8080"
          export HTTPS_PROXY="http://192.168.123.249:8080"
      notify: Reload Bashrc

  handlers:
    - name: Reload Bashrc
      ansible.builtin.command: source ~/.bashrc