/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "scan.h"

bool_t
xdr_ResultFile (XDR *xdrs, ResultFile *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->numch))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numwords))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numlines))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Name (XDR *xdrs, Name *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->name, 25,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ResultDir (XDR *xdrs, ResultDir *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->num_file))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->names, 8,
		sizeof (Name), (xdrproc_t) xdr_Name))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_RequestDir (XDR *xdrs, RequestDir *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->num))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->dirName, ~0))
		 return FALSE;
	return TRUE;
}
